drop table if exists card_rides;
drop table if exists user_rides;
drop table if exists cards;
drop table if exists users;
drop table if exists bus_lines;
drop table if exists bus_names;
drop table if exists buildings;
drop table if exists entrances;
drop table if exists line_details;
drop table if exists stations;
drop table if exists `lines`;
create table if not exists buildings ( building_id int  null, entrance_id int  null, entrance    tinytext null);
create table if not exists bus_lines (busline_id int  null, busname_id int  null, busline    tinytext null); 
create table if not exists bus_names (busname_id  int  null, entrance_id int  null, busname tinytext null); 
create table if not exists card_rides (ride_id serial null, card_id  tinytext null, business_carriage int, on_the_ride int not null, from_station int  null, to_station   int  null, price    double   null, start_time   tinytext null, end_time tinytext null);
create table if not exists cards (card_number tinytext null, money   double   null, create_time tinytext null);  
create table if not exists entrances (entrance_id   int  null, station_id    int  null, entrance_name tinytext null);  
create table if not exists line_details (line_id int not null, station_id int null, line_num   int null);
create table if not exists `lines` (line_id   serial not null, line_name varchar(10) not null, business_carriage int, start_time    tinytext null, end_time  tinytext null, intro     text null, mileage   tinytext null, color     tinytext null, first_opening date null, url   tinytext null);
create table if not exists stations (station_id   serial not  null, english_name varchar(900) null, chinese_name varchar(900) null, district varchar(900) null, status varchar(10), introduction text     null);
create table if not exists user_rides (ride_id  serial not null, user_id  tinytext null, business_carriage int, on_the_ride int not null, from_station int  null, to_station   int  null, price    double   null, start_time   tinytext null, end_time tinytext null);
create table if not exists users (user_id_number tinytext null, name   tinytext null, phone  tinytext null, gender     char null, district   tinytext null);
use project1;